export default {
  Reasons: [
    "I love you because you always manage to laugh at my jokes, even when they are not all that funny.",
    " I love you because you have always been so supportive of me and my dreams in ways that I could not have imagined.",
    "I love that I can just be myself with you. I do not have to pretend to be anyone else for you to love me.",
    "I love you because you have such a special ability to see the good in everyone and in every situation.",
    "I love you because you are not afraid to open up to me about your feelings, both the good and the bad things. I love that you can easily trust me with how you feel, no matter what it is.",
    "I love you because whenever I am with you, it is like we are in our own special little world together where nobody else exists.",
    "I love you because you have never allowed any distance to get between us or separate us. No matter how far apart we are, my heart is always with you and your heart is always with mine. And I love that I never have to worry about that.",
    "I love you because you stay true to who you are. No matter how much things have changed over the years, you are still the same person inside.",
    "I love you because ever since you came into my life, I laugh harder, smile more, and cry a lot less. You have been good for me.",
    "I love you because your hugs, kisses, and warm embrace bring me so much comfort and happiness to me.",
    "I love you because your hugs make me feel like the luckiest person alive.",
    "You have such a beautiful smile that lights up my day.",
    "Your positive attitude towards life… The way you see the world makes me want to be a better person!",
    "I love you because because you are you",
    "I love you because you are crazy",
    "I love you because you have the most beautiful eyes ever",
    "I love you because you have the most beautiful heart ever",
    "I love you because you have the softest hands",
    "I love you because because you always smile",
    "I love you because because of your courage after all you ve been through",
    "I love you because because you never gave up and you insisted to fight back life",
    "I love you because because you like adidas :p",
    "I love you because because you care",
    "I love you because even when we are apart, I know you are with me.",
    "We have so many ridiculous nicknames.",
    "I love how you always respect people.",
    "You are such a good cook azdee popcorn ehh :p .",
    "I love how we form a great team.",
    "you always reply to my messages and jokes on the rcg group",
    "your favorite hobby is to sleep",
  ],

  Remember: [
    "our first date",
    "W.M when we saw him near your village",
    "asking for tea after eating chocolate",
    "dancing hand",
    " jouney in byblos",
    "while filming a video in south lebanon, there were an accident behind us",
    "Sunset on your birthday, one of the best days ever",
    "i surprised you when i came to visit you after the explosion",
    "while drinking tea on our way back from harissa the electricity cut off ",
    "when my car didn't start after we went to starbucks to study",
    "when i texted you for the first time on your phone",
    "you drove my car when we were in your village",
    "remember when you were drinving and i was cutting the sun's light from your face",
    "7 nov 2021",
    "beb2a be7kik bwad3ak",
    "I love your sense of family and your dedication to the ones you love.",
    "you sent me a oic of you 3am tono2re koussa :p",
    "we stayed one day at work angry of each other and i sent you a note ",
    "you made a cake on my birthday, you were in bask",
    "we light up the candle together in harissa",
    "you laughed at me feets :p",
    
  ],

  HaveToDo: [
    "10 squads",
    "give me 5 kisses",
    "take a pic with your mom",
    "eat a banana",
    "drink tea",
    "watch a movie together",
    "listen to a song of your choice together",
    "go crazy for 1 min",
    "2rosse charbel :P",
    "drink 2 cups of water in front of me",
    "put lipstick in front of me",
    "send me 3 selfies during the day",
    "put facial creme in front of me",
    "bye me loto tickets worth 30,000lbp",
    "prepare lemonade by yourself",
    "draw me something",
    "dress crazy and funny clothes",
    "choose three ingredients at home and mix them to prepare something new to eat, be creative",
    "draw on your hand a heart",
    "call nicolas and charbel in from of me and tell them that you are getting married tomorow",
    "tell me a secret",
    "choose the book go to page 46 , line 8, 5th word what is it?",
    "wear different shoes pair and walk for 1 hour at home",
    "put a facial mask and scare me :p",
  ],
};
